### ISSUE TITLE
Conversion of an array with ndim > 0 to a scalar is deprecated

### ISSUE THREAD

**Issue by aelnosu** [kiddykene/humannumguesser#3]
main.py:233: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)

**Comment by Ubuntufanboy** [comment]
You can use an older version of numpy with
```
pip3 install numpy=1.18.5
```

**Comment by aelnosu** [comment]
#6
